name: SNAPSHOT with sources.jar

on:
  push:

  # trigger when starred
  watch:
    types: [started]  
    
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: ./gradlew publish -b sources.gradle.kts
      env:
        USERNAME: token
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
